// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/unicoooorn/pingr/internal/model"
)

// NewMockAlertGenerator creates a new instance of MockAlertGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertGenerator {
	mock := &MockAlertGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAlertGenerator is an autogenerated mock type for the AlertGenerator type
type MockAlertGenerator struct {
	mock.Mock
}

type MockAlertGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertGenerator) EXPECT() *MockAlertGenerator_Expecter {
	return &MockAlertGenerator_Expecter{mock: &_m.Mock}
}

// GenerateAlertMessage provides a mock function for the type MockAlertGenerator
func (_mock *MockAlertGenerator) GenerateAlertMessage(ctx context.Context, subsystemInfoByName map[string]model.SubsystemInfo) (string, error) {
	ret := _mock.Called(ctx, subsystemInfoByName)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAlertMessage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]model.SubsystemInfo) (string, error)); ok {
		return returnFunc(ctx, subsystemInfoByName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]model.SubsystemInfo) string); ok {
		r0 = returnFunc(ctx, subsystemInfoByName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]model.SubsystemInfo) error); ok {
		r1 = returnFunc(ctx, subsystemInfoByName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAlertGenerator_GenerateAlertMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAlertMessage'
type MockAlertGenerator_GenerateAlertMessage_Call struct {
	*mock.Call
}

// GenerateAlertMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - subsystemInfoByName map[string]model.SubsystemInfo
func (_e *MockAlertGenerator_Expecter) GenerateAlertMessage(ctx interface{}, subsystemInfoByName interface{}) *MockAlertGenerator_GenerateAlertMessage_Call {
	return &MockAlertGenerator_GenerateAlertMessage_Call{Call: _e.mock.On("GenerateAlertMessage", ctx, subsystemInfoByName)}
}

func (_c *MockAlertGenerator_GenerateAlertMessage_Call) Run(run func(ctx context.Context, subsystemInfoByName map[string]model.SubsystemInfo)) *MockAlertGenerator_GenerateAlertMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]model.SubsystemInfo
		if args[1] != nil {
			arg1 = args[1].(map[string]model.SubsystemInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAlertGenerator_GenerateAlertMessage_Call) Return(s string, err error) *MockAlertGenerator_GenerateAlertMessage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAlertGenerator_GenerateAlertMessage_Call) RunAndReturn(run func(ctx context.Context, subsystemInfoByName map[string]model.SubsystemInfo) (string, error)) *MockAlertGenerator_GenerateAlertMessage_Call {
	_c.Call.Return(run)
	return _c
}
