// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAlertSender creates a new instance of MockAlertSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertSender {
	mock := &MockAlertSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAlertSender is an autogenerated mock type for the AlertSender type
type MockAlertSender struct {
	mock.Mock
}

type MockAlertSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertSender) EXPECT() *MockAlertSender_Expecter {
	return &MockAlertSender_Expecter{mock: &_m.Mock}
}

// Poll provides a mock function for the type MockAlertSender
func (_mock *MockAlertSender) Poll(ctx context.Context) ([]string, []string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 []string
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, []string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []string); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAlertSender_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockAlertSender_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertSender_Expecter) Poll(ctx interface{}) *MockAlertSender_Poll_Call {
	return &MockAlertSender_Poll_Call{Call: _e.mock.On("Poll", ctx)}
}

func (_c *MockAlertSender_Poll_Call) Run(run func(ctx context.Context)) *MockAlertSender_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAlertSender_Poll_Call) Return(starts []string, stops []string, err error) *MockAlertSender_Poll_Call {
	_c.Call.Return(starts, stops, err)
	return _c
}

func (_c *MockAlertSender_Poll_Call) RunAndReturn(run func(ctx context.Context) ([]string, []string, error)) *MockAlertSender_Poll_Call {
	_c.Call.Return(run)
	return _c
}

// SendAlert provides a mock function for the type MockAlertSender
func (_mock *MockAlertSender) SendAlert(ctx context.Context, alertMessage string, infographics []byte) error {
	ret := _mock.Called(ctx, alertMessage, infographics)

	if len(ret) == 0 {
		panic("no return value specified for SendAlert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, alertMessage, infographics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAlertSender_SendAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAlert'
type MockAlertSender_SendAlert_Call struct {
	*mock.Call
}

// SendAlert is a helper method to define mock.On call
//   - ctx context.Context
//   - alertMessage string
//   - infographics []byte
func (_e *MockAlertSender_Expecter) SendAlert(ctx interface{}, alertMessage interface{}, infographics interface{}) *MockAlertSender_SendAlert_Call {
	return &MockAlertSender_SendAlert_Call{Call: _e.mock.On("SendAlert", ctx, alertMessage, infographics)}
}

func (_c *MockAlertSender_SendAlert_Call) Run(run func(ctx context.Context, alertMessage string, infographics []byte)) *MockAlertSender_SendAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAlertSender_SendAlert_Call) Return(err error) *MockAlertSender_SendAlert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAlertSender_SendAlert_Call) RunAndReturn(run func(ctx context.Context, alertMessage string, infographics []byte) error) *MockAlertSender_SendAlert_Call {
	_c.Call.Return(run)
	return _c
}
