// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/unicoooorn/pingr/internal/model"
)

// NewMockInfographicsRenderer creates a new instance of MockInfographicsRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInfographicsRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInfographicsRenderer {
	mock := &MockInfographicsRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInfographicsRenderer is an autogenerated mock type for the InfographicsRenderer type
type MockInfographicsRenderer struct {
	mock.Mock
}

type MockInfographicsRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInfographicsRenderer) EXPECT() *MockInfographicsRenderer_Expecter {
	return &MockInfographicsRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type MockInfographicsRenderer
func (_mock *MockInfographicsRenderer) Render(ctx context.Context, infos map[string]model.SubsystemInfo) ([]byte, error) {
	ret := _mock.Called(ctx, infos)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]model.SubsystemInfo) ([]byte, error)); ok {
		return returnFunc(ctx, infos)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]model.SubsystemInfo) []byte); ok {
		r0 = returnFunc(ctx, infos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]model.SubsystemInfo) error); ok {
		r1 = returnFunc(ctx, infos)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInfographicsRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockInfographicsRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - infos map[string]model.SubsystemInfo
func (_e *MockInfographicsRenderer_Expecter) Render(ctx interface{}, infos interface{}) *MockInfographicsRenderer_Render_Call {
	return &MockInfographicsRenderer_Render_Call{Call: _e.mock.On("Render", ctx, infos)}
}

func (_c *MockInfographicsRenderer_Render_Call) Run(run func(ctx context.Context, infos map[string]model.SubsystemInfo)) *MockInfographicsRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]model.SubsystemInfo
		if args[1] != nil {
			arg1 = args[1].(map[string]model.SubsystemInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInfographicsRenderer_Render_Call) Return(bytes []byte, err error) *MockInfographicsRenderer_Render_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockInfographicsRenderer_Render_Call) RunAndReturn(run func(ctx context.Context, infos map[string]model.SubsystemInfo) ([]byte, error)) *MockInfographicsRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}
