// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/unicoooorn/pingr/internal/model"
)

// NewMockMetricsExtractor creates a new instance of MockMetricsExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsExtractor {
	mock := &MockMetricsExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsExtractor is an autogenerated mock type for the MetricsExtractor type
type MockMetricsExtractor struct {
	mock.Mock
}

type MockMetricsExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsExtractor) EXPECT() *MockMetricsExtractor_Expecter {
	return &MockMetricsExtractor_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function for the type MockMetricsExtractor
func (_mock *MockMetricsExtractor) Extract(ctx context.Context, subsystem string) (model.MetricsExtractorResult, error) {
	ret := _mock.Called(ctx, subsystem)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 model.MetricsExtractorResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.MetricsExtractorResult, error)); ok {
		return returnFunc(ctx, subsystem)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.MetricsExtractorResult); ok {
		r0 = returnFunc(ctx, subsystem)
	} else {
		r0 = ret.Get(0).(model.MetricsExtractorResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subsystem)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricsExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockMetricsExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - subsystem string
func (_e *MockMetricsExtractor_Expecter) Extract(ctx interface{}, subsystem interface{}) *MockMetricsExtractor_Extract_Call {
	return &MockMetricsExtractor_Extract_Call{Call: _e.mock.On("Extract", ctx, subsystem)}
}

func (_c *MockMetricsExtractor_Extract_Call) Run(run func(ctx context.Context, subsystem string)) *MockMetricsExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsExtractor_Extract_Call) Return(metricsExtractorResult model.MetricsExtractorResult, err error) *MockMetricsExtractor_Extract_Call {
	_c.Call.Return(metricsExtractorResult, err)
	return _c
}

func (_c *MockMetricsExtractor_Extract_Call) RunAndReturn(run func(ctx context.Context, subsystem string) (model.MetricsExtractorResult, error)) *MockMetricsExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}
